# Generated by Django 5.0.11 on 2025-02-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_wizard", "0004_alter_holidayrangeperiodmodel_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holidayrangeperiodmodel",
            name="country",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="holidayrangeperiodmodel",
            name="holiday",
            field=models.CharField(max_length=255),
        ),
    ]
