#!/bin/sh

versions="python:3.10-slim-bullseye,3.9"

for vers in $versions; do
  IFS="," read dockerfile_version additional_python_version <<EOF
$vers
EOF

  export IMAGE="time-wizard-unittest-$dockerfile_version"
  export DOCKERFILE_VERSION=$dockerfile_version
  export ADDITIONAL_PYTHON_VERSION=$additional_python_version

  echo "==============================="
  echo "tests: $IMAGE"
  echo "===============================\n"

  envsubst '${DOCKERFILE_VERSION} ${ADDITIONAL_PYTHON_VERSION}' < Dockerfile.tests.needs-envsubst > /tmp/Dockerfile.tests-dtw
  docker build . -f /tmp/Dockerfile.tests-dtw -t $IMAGE
  docker_compose="docker compose -f $(dirname $0)/run-tests.compose.yaml"

  $docker_compose run test tox
  $docker_compose down -v

  echo "\n\n"
done
